services:
  - type: web
    name: anonymous-bot
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: USE_WEBHOOK
        value: "true"
      - key: BOT_TOKEN
        sync: false
      - key: ADMIN_IDS
        sync: false
      - key: WEBHOOK_URL
        fromService:
          type: web
          name: anonymous-bot
          property: host
